import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { GetSessionParams, getSession, signIn, signOut, useSession } from "next-auth/react";
import { useState } from "react";
import Image from "next/image";
import { api } from "~/utils/api";
import { IoSparklesSharp } from "react-icons/io5";

const Profile: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Stake Chatbot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-5 flex justify-center ">
        <div className="flex max-w-5xl flex-col items-center">
         <h1>Success !</h1>
        </div>
      </main>
    </>
  );
};


export default Profile;
