import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useState } from "react";
import Image from "next/image";
import { api } from "~/utils/api";
import Audit from "~/components/Audit";

const AuditPage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Stake Chatbot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-20 flex w-full flex-col items-center justofy-center">
       <Audit/>
      </main>
    </>
  );
};

export default AuditPage;